# Generated by Django 2.1.7 on 2019-05-29 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieList',
            fields=[
                ('movie_id', models.IntegerField(primary_key=True, serialize=False)),
                ('movie_name', models.CharField(max_length=50)),
                ('movie_cast', models.CharField(max_length=200)),
                ('movie_ratings', models.CharField(max_length=4)),
            ],
        ),
    ]
