# Generated by Django 2.2.1 on 2019-06-01 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviesapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movielist',
            name='movie_name',
            field=models.CharField(max_length=200),
        ),
    ]
